#!/bin/sh

case "$1" in
wait)
	case "$2" in
		start)
			echo database
			;;
		stop)
			echo frontend
			;;
	esac
	;;
auto)
	case "$2" in
		start)
			echo database
			;;
	esac
	;;
mark)
	echo backend
	;;
lock)
	echo application_exclusive
	;;
start)
	echo -n 'apache start enter ...'
	sleep 0.01
	echo '... apache start leave'
	;;
stop)
	;;
esac
