#!/bin/sh

case "$1" in
wait)
	case "$2" in
		start)
			echo backend application apache
			;;
		stop)
			;;
	esac
	;;
auto)
	case "$2" in
		start)
			echo backend application
			;;
	esac
	;;
mark)
	echo frontend
	;;
start)
	;;
stop)
	;;
esac
