#!/bin/sh

JET9_MULTITASK_FLOW_CLI_DISABLE=1

. ../../jet9-multitask-flow

LOCK_DIR=/tmp/mti-lock.$$

mkdir $LOCK_DIR

# arguments: task action
task_execute() {
	echo "execute $1 $2"
}

dependency_init network iscsi_login nfs_mount virtual_machines

# start virtual machines when iscsi disks and NFS mounts are ready
dependency_run 'virtual_machines start' 'iscsi_login nfs_mount' &

# start nfs mounts when network is ready
dependency_run 'nfs_mount start' 'network' &

# start ISCSI when network is ready
dependency_run 'iscsi_login start' 'network' &

# start network without dependencies
dependency_run 'network start' &

wait

rmdir $LOCK_DIR
