#!/bin/sh

JET9_MULTITASK_FLOW_CLI_DISABLE=1

. ../../jet9-multitask-flow

LOCK_DIR=/tmp/mti-lock.$$

mkdir $LOCK_DIR

dependency_init apache unicorn mysql postgresql nginx database frontend backend

task_execute() {
	eval run_$1
}

run_nginx() {
	echo run nginx
}

run_apache() {
	echo run apache
}

run_unicorn() {
	echo run unicorn
}

run_mysql() {
	echo run mysql
}

run_postgresql() {
	echo run postgresql
}


## define virtual tasks

# wait apache and unicorn, than mark backend
dependency_run '' 'apache unicorn' 'backend' &

# wait mysql and postgresql, than mark database
dependency_run '' 'mysql postgresql' 'database' &

# wait nginx, than mark frontend
dependency_run '' 'nginx' 'frontend' &


## define real tasks

# run nginx when all backends are ready
dependency_run 'nginx' 'backend' &

# run apache when all databases are ready
dependency_run 'apache' 'database' &

# run unicorn when mysql is ready 
dependency_run 'unicorn' 'mysql' &

# run mysql without dependencies
dependency_run 'mysql' &

# run postgresql without dependencies
dependency_run 'postgresql' &

wait

rmdir $LOCK_DIR
